---
version: "3.0"
services:
  traefik: 
    image: "traefik:v2.1.0"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api.insecure
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  web:
    build: ./backend/
    labels:
      - traefik.enable=true 
      - traefik.http.routers.api.rule=Host(`api.kschoon.me`) || PathPrefix(`/api`)
      - traefik.http.middlewares.strip_api.stripprefix.prefixes=/api
      - traefik.http.routers.api.middlewares=strip_api@docker
