---
version: "3.0"
services:
  traefik: 
    image: "traefik:v2.1.0"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api.insecure
      - --accessLog
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  web:
    build: ./backend/
    restart: unless-stopped
    command: /start-reload.sh
    environment:
      - LOG_LEVEL=debug
    depends_on:
      - db
    volumes:
      - "./backend/:/app/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - traefik.enable=true 
      - traefik.http.routers.api.rule=Host(`localhost`)
  db:
    image: "postgres:12"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
