---
version: "3.5"
services:
  traefik:
    image: "traefik:v2.2.0"
    command:
      - --entryPoints.web.address=:80/tcp
      - --providers.docker=true
      - --api.insecure
      - --accessLog
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - web
      - faktory

  web:
    # Image/build/volumes specified in docker-compose.{production, override}.yml
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_HOST=db
    labels:
      - traefik.enable=true

  faktory:
    image: "contribsys/faktory"
    restart: unless-stopped
    ports:
      - "7420:7420"
      - "7419:7419"
    # Traefik host is specified in docker-compose.{production, override}.yml
    labels:
      - traefik.enable=true
      - traefik.http.services.faktory-kschoonme.loadbalancer.server.port=3000
  faktory_worker:
    # Image/build/volmes specified in docker-compose.{production, override}.yml
    labels:
      - traefik.enable=false
    depends_on:
      - faktory

  notifications:
    # Image/build/volumes specified in docker-compose.{production, override}.yml
    labels:
      - traefik.enable=false

  sso:
    # Image/build/volumes specified in docker-compose.{production, override}.yml
    restart: unless-stopped
    environment:
      - USE_REDIS=true
    # Traefik host is specified in docker-compose.{production, override}.yml
    labels:
      - traefik.enable=true
      - traefik.http.services.sso-kschoonme.loadbalancer.server.port=3000
  identity:
    # Image/build/volumes specified in docker-compose.{production, override}.yml
    labels:
      - traefik.enable=false
    environment:
      - POSTGRES_URL="postgres://postgres:postgres@db:5432"

  # redis/Database defined in docker-compose.override.yml
