---
version: "3.5"
services:
  traefik:
    image: "traefik:v2.2.0"
    command:
      - --entryPoints.web.address=:80/tcp
      - --providers.docker=true
      - --api.insecure
      - --accessLog
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - web
      - faktory
  web:
    # Image/build/volumes specified in docker-compose.{production, override}.yml
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_HOST=db
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`localhost`)
  faktory:
    image: "contribsys/faktory"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jobs.rule=Host(`localhost`) && PathPrefix(`/faktory/`)
    ports:
      - "7420:7420"
      - "7419:7419"
  faktory_worker:
    # Image/build/volmes specified in docker-compose.{production, override}.yml
    labels:
      - traefik.enable=false
    depends_on:
      - faktory
  notifications:
    # Image/build/volumes specified in docker-compose.{production, override}.yml
    labels:
      - traefik.enable=false
  db:
    image: "postgres:12"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_PASSWORD=postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
