---
version: "3.5"
services:
  traefik:
    image: "traefik:v2.1.0"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.secureweb.address=:443
      - --providers.docker=true
      - --api
      - --certificatesResolvers.tls_resolver.acme.email=me@kschoon.me
      - --certificatesResolvers.tls_resolver.acme.storage=/acme.json
      - --certificatesResolvers.tls_resolver.acme.httpChallenge.entryPoint=web
    labels:
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.dashboard.rule=Host(`traefik.${KSCHOONME_DOMAIN:-kschoon.me}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=tls_resolver
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
  faktory_worker:
    image: "kschoonme/faktory-worker:latest"
    env_file:
      - ./backend/.env

  web:
    image: "kschoonme/backend:latest"
    labels:
      - traefik.http.routers.api.rule=Host(`api.${KSCHOONME_DOMAIN:-kschoon.me}`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=tls_resolver
      - traefik.http.services.web-kschoonme.loadbalancer.server.port=8080
    env_file:
      - ./backend/.env

  faktory:
    labels:
      - traefik.http.routers.faktory.rule=Host(`faktory.${KSCHOONME_DOMAIN:-kschoon.me}`)
      - traefik.http.routers.faktory.tls=true
      - traefik.http.routers.faktory.tls.certresolver=tls_resolver
      - traefik.http.services.faktory-kschoonme.loadbalancer.server.port=7420
    env_file:
     - ./.docker/faktory.env
    environment:
      - PRODUCTION=true
  faktory_worker:
    image: "kschoonme/faktory-worker:latest"

  notifications:
    image: "kschoonme/notifications:latest"

  sso:
    image: "kschoonme/sso:latest"
    env_file:
     - ./.docker/sso.env
    labels:
      - traefik.http.routers.sso.rule=Host(`sso.${KSCHOONME_DOMAIN:-kschoon.me}`)
      - traefik.http.routers.sso.tls=true
      - traefik.http.routers.sso.tls.certresolver=tls_resolver
    environment:
      - ISSUER=https://sso.kschoon.me
  identity:
    image: "kschoonme/identity:latest"
