---
version: "3.5"
services:
  web:
    build:
      context: ./backend/
      target: rust-base
    volumes:
      - "./backend/:/usr/src/backend/"
    labels:
      - traefik.http.routers.api.rule=Host(`lvh.me`)

  faktory:
    labels:
      - traefik.http.routers.jobs.rule=Host(`faktory.lvh.me`)
  faktory_worker:
    build:
      context: ./backend/worker/
      target: development
    volumes:
      - "./backend/worker/:/usr/src/worker/"
      - "./backend/.env:/usr/src/worker/.env"

  notifications:
    build:
      context: ./notifications/
      target: development
    volumes:
      - "./notifications/:/usr/src/notifications/"

  sso:
    build:
      context: ./sso/
      target: development
    volumes:
      - "./sso/:/usr/src/sso/"
    labels:
      - traefik.http.routers.sso.rule=Host(`sso.lvh.me`)
    environment:
      - ISSUER=http://sso.lvh.me
  identity:
    build:
      context: ./identity/
      target: development
    volumes:
      - "./identity/:/usr/src/identity/"

  db:
    image: "postgres:12"
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_PASSWORD=postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    # command and volume is overridden in docker-compose.production.yml
    image: "redis:6-alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"
