---
version: "3.5"
services:
  db:
    ports:
      - "5432:5432"
  web:
    build:
      context: ./backend/
      target: rust-base
    volumes:
      - "./backend/:/usr/src/backend/"
  faktory_worker:
    build:
      context: ./backend/worker/
      target: development
    volumes:
      - "./backend/worker/:/usr/src/worker/"
      - "./backend/.env:/usr/src/worker/.env"
  notifications:
    build:
      context: ./notifications/
      target: development
    volumes:
      - "./notifications/:/usr/src/notifications/"

  identity:
    build:
      context: ./identity/
      target: development
    volumes:
      - "./identity/:/usr/src/identity/"

  sso:
    build:
      context: ./sso/
      target: development
    volumes:
      - "./sso/:/usr/src/sso/"
