---
- name: "Install docker on the host"
  include: ./docker.yml

- name: "Create the API user"
  user:
    name: "{{ API_USER }}"
    comment: "User responsible for managing the API"
    system: yes
    groups:
      - docker
  become: yes

- name: "Clone the kschoon.me repo"
  git:
    repo: "https://github.com/kevinschoonover/kschoon.me.git"
    dest: "{{ API_INSTALLATION_DIR }}"
    version: "terraform-azure"
  become: yes

- name: "Update the API installation directory permissions"
  file:
    path: "{{ API_INSTALLATION_DIR }}"
    owner: "{{ API_USER }}"
    state: directory
    recurse: yes
  become: yes

- name: "Create the .env file for the backend"
  template:
    src: "web.env.j2"
    dest: "{{ API_INSTALLATION_DIR }}/backend/.env"
    owner: "{{ API_USER }}"
  become: yes
  become_user: "{{ API_USER }}"


- name: "Create the .env file for the faktory container"
  template:
    src: "faktory.env.j2"
    dest: "{{ API_INSTALLATION_DIR }}/.docker/faktory.env"
    owner: "{{ API_USER }}"
  become: yes
  become_user: "{{ API_USER }}"


- name: "See if acme file exists"
  stat:
    path: "{{ ACME_FILE_PATH }}"
  register: acme_file

- name: "Create or update the acme.json"
  file:
    path: "{{ ACME_FILE_PATH }}"
    owner: "{{ API_USER }}"
    state: "{{ 'file' if  acme_file.stat.exists else 'touch' }}"
    mode: 0600
  become: yes
  become_user: "{{ API_USER }}"


- name: "Start the API"
  vars:
    DOCKER_DIR: "{{ API_INSTALLATION_DIR }}/"
  docker_compose:
    pull: yes
    files:
      - docker-compose.yml
      - docker-compose.production.yml
    project_src: "{{ DOCKER_DIR }}"
  become: yes
  become_user: "{{ API_USER }}"

