---
- name: "Create the API user"
  user:
    name: "{{ API_USER }}"
    comment: "User responsible for managing the API"
    system: yes
    groups:
      - docker

- name: "Clone the kschoon.me repo"
  git:
    repo: "https://github.com/kevinschoonover/kschoon.me.git"
    dest: "{{ API_INSTALLATION_DIR }}"
    version: "master"

- name: "Update the API installation directory permissions"
  file:
    path: "{{ API_INSTALLATION_DIR }}"
    owner: "{{ API_USER }}"
    state: directory
    recurse: yes

- name: "See if acme file exists"
  stat:
    path: "{{ ACME_FILE_PATH }}"
  register: acme_file

- name: "Create or update the acme.json"
  file:
    path: "{{ ACME_FILE_PATH }}"
    owner: "{{ API_USER }}"
    state: "{{ 'file' if  acme_file.stat.exists else 'touch' }}"
    mode: 0600

- name: "Install the pip3 python dependency manager"
  package:
    name: python3-pip
    state: present

- name: "Install the docker python modules"
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: "Start the API"
  vars:
    DOCKER_DIR: "{{ API_INSTALLATION_DIR }}/"
  docker_compose:
    build: yes
    files:
      - docker-compose.yml
      - docker-compose.production.yml
    project_src: "{{ DOCKER_DIR }}"
