version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
      - image: circleci/postgres:12-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: ~/kschoon.me/backend
    steps:
      - checkout:
          path: ~/kschoon.me
      - restore_cache:
          keys: 
            - deps1-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run: poetry install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths: 
            - ~/.cache/pypoetry/virtualenvs
      - run: poetry run pytest --cov-report=xml --cov=app
      - codecov/upload:
          file: ./coverage.xml
