version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
      - image: circleci/postgres:9.6.7
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: ~/kschoon.me/backend
    steps:
      - checkout:
          path: ~/kschoon.me
      - restore_cache:
          keys: 
            - deps1-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run: poetry install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths: 
            - ~/.cache/pypoetry/virtualenvs
      - run: poetry run pytest
