---
- name: Install Nomad
  hosts: nomad_instances
  vars:
      nomad_node_role: "both"
  roles:
    - ansible-nomad

  tasks:
    - name: Allow nomad ui with ufw
      ufw: 
        rule: allow
        port: "4646" 
